### ISSUE TITLE
Uncaught TypeError: editor.getSelectedText is not a function

### ISSUE THREAD

**Issue by jecky2013** [gwomacks/php-debug#101]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.4

### Stack Trace

Uncaught TypeError: editor.getSelectedText is not a function

```
At /Users/kdsc/.atom/packages/php-debug/lib/php-debug.coffee:167

TypeError: editor.getSelectedText is not a function
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/Users/kdsc/.atom/packages/php-debug/lib/php-debug.coffee:167:34)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Users/kdsc/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:94:25)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/kdsc/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:152:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Users/kdsc/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (/Users/kdsc/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:56 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:53 editor:log-cursor-scope (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -3:34.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:27 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:25.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:25.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
 16x -3:18.8.0 editor:select-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpmd",
      "linter-phpcs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-autocomplete-php, v0.18.1
atom-terminal-panel, v4.4.4
autocomplete-paths, v1.0.2
color-picker, v2.0.13
emmet, v2.3.15
language-mongodb, v0.3.1
linter, v1.11.3
minimap, v4.16.2
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.1
php-debug, v0.1.4
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Hopefully fixed in v0.2.2 - Released Today

**Comment by cosmolux** [comment]
I triggered this by right-clicking in a field in settings.  FWIW I was trying to see if I could copy the default value for the Non Word Characters field.

**Comment by gigmaps** [comment]
triggered this by right-clicking in Find & Replace File/directory pattern

**Comment by TamasBarta** [comment]
I triggered this by right-clicking Markdown Preview Plus' preview.

**Comment by seanmars** [comment]
I triggered this by right-clicking all input field (Installed Packages, Installed Themes, Install Packages)

**Comment by MohammedAl-Mahdawi** [comment]
[Enter steps to reproduce below:]

1. Right click in the "Font Family" settings field.

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3


### Stack Trace

Uncaught TypeError: editor.getSelectedText is not a function

```
At /home/mohammed/.atom/packages/php-debug/lib/php-debug.coffee:196

TypeError: editor.getSelectedText is not a function
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/home/mohammed/.atom/packages/php-debug/lib/php-debug.coffee:196:34)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:110:19)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:89:33)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:168:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -9:46 core:move-down (atom-text-editor.editor.mini.is-focused)
     -9:45.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -9:44.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:16.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
 14x -7:51.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -7:49 core:move-up (atom-text-editor.editor.mini.is-focused)
  6x -7:47.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:44.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -3:49.6.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  3x -0:46.4.0 core:paste (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -0:10.1.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-ctags, v4.5.2
autocomplete-php, v0.3.7
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.13
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-phpcs, v1.4.0
linter-phpmd, v1.5.0
linter-scss-lint, v3.0.4
linter-tidy, v2.1.1
minimap, v4.24.3
php-debug, v0.2.3
project-manager, v2.9.7
wordpress-api, v1.2.2

# Dev
No dev packages
```
