### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setActive' of undefined

### ISSUE THREAD

**Issue by javierLinan** [gwomacks/php-debug#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: linux 3.13.0-74-generic
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setActive' of undefined

```
At /home/javier/.atom/packages/php-debug/lib/php-debug.coffee:257

TypeError: Cannot read property 'setActive' of undefined
  at Object.module.exports.PhpDebug.toggleDebugging (/home/javier/.atom/packages/php-debug/lib/php-debug.coffee:257:18)
  at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (/home/javier/.atom/packages/php-debug/lib/php-debug.coffee:102:93)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:00.9 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "php-debug": {
    "ServerPort": 15000
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-chai-snippets, v0.3.0
coffee-navigator, v0.0.16
color-picker, v1.7.0
cucumber, v0.5.0
docblockr, v0.6.3
editorconfig, v1.2.0
highlight-line, v0.10.2
language-vue, v0.8.0
linter, v0.12.2
linter-coffeelint, v0.2.3
linter-cpplint, v1.0.0
linter-js-yaml, v1.0.0
linter-jshint, v0.1.4
minimap, v4.8.0
php-debug, v0.2.1

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Hopefully fixed in v0.2.2 - Released Today
