### ISSUE TITLE
php-debug fails to start

### ISSUE THREAD

**Issue by rschalch** [gwomacks/php-debug#109]
That's what i receive from stack trace:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Ubuntu 15.10
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.1

### Stack Trace

Failed to activate the php-debug package

```
At Cannot find module '../object/pairs'

Error: Cannot find module '../object/pairs'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/internal/getMatchData.js:2:13)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/internal/baseMatches.js:2:20)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/internal/baseIteratee.js:1:98)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/every.js:3:20)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/XMLElement.js:13:11)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/XMLElement.js:212:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/XMLBuilder.js:11:16)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/XMLBuilder.js:69:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:7:16)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:13:13)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:538:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/lib/engines/dbgp/dbgp.coffee:1:15)
    at Object.<anonymous> (/home/rbs/.atom/packages/php-debug/lib/engines/dbgp/dbgp.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.module.exports.PhpDebug.activate (/home/rbs/.atom/packages/php-debug/lib/php-debug.coffee:120:12)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:170:19)
    at /opt/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:517:21)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:57.6.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "wombat-light-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "styleguide",
      "timecop",
      "gulp-control",
      "language-c",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-toml",
      "go-to-line",
      "autosave",
      "autocomplete-atom-api",
      "bezier-curve-editor",
      "atom-css-comb",
      "atom-terminal"
    ],
    "packagesWithKeymapsDisabled": [
      "bezier-curve-editor",
      "block-comment",
      "block-comment-lines",
      "expose",
      "tab-switcher",
      "project-ring",
      "erb-helper",
      "advanced-open-file",
      "theme-toggler",
      "compare-files",
      "sublime-block-comment",
      "comment-headers",
      "csscomb",
      "color-picker",
      "atom-autocomplete-php"
    ]
  },
  "php-debug": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.15
api-docs, v0.0.3
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-ternjs, v0.13.2
autoclose-html, v0.19.0
chary-tree-view, v0.2.3
codeigniter, v0.2.0
color-picker, v2.0.14
editorconfig, v1.2.4
emmet, v2.3.18
feedback, v0.38.0
file-icons, v1.6.14
git-hide, v0.1.2
html-entities, v0.4.0
keyboard-localization, v1.4.14
linter, v1.11.3
linter-php, v1.1.6
metrics, v0.53.1
minimap, v4.19.0
php-debug, v0.2.1
pigments, v0.20.0
project-ring, v0.36.2
sync-settings, v0.6.0
tasks, v2.6.0
typewriter, v0.3.5
vim-mode, v0.64.0
wombat-light-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Closing for now, please reopen if a reinstall of the latest release does not resolve.
