### ISSUE TITLE
TypeError: this.settingsView.destroy is not a function

### ISSUE THREAD

**Issue by rugk** [gwomacks/php-debug#113]
[Enter steps to reproduce below:]

1. After some time not using the package I tried to close it.

**Atom Version**: 1.4.0
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.4

### Stack Trace

Uncaught TypeError: this.settingsView.destroy is not a function

```
At /D:/Users/%username%/.atom/packages/php-debug/lib/php-debug.coffee:460

TypeError: this.settingsView.destroy is not a function
    at Object.module.exports.PhpDebug.toggleDebugging (file:///D:/Users/%username%/.atom/packages/php-debug/lib/php-debug.coffee:253:21)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (file:///D:/Users/%username%/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -9:00.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:17 core:backspace (atom-text-editor.editor.is-focused)
  6x -4:16.5.0 core:delete (atom-text-editor.editor.is-focused)
     -4:14.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:14.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:11.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:11.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:11.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:10.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:37.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:11.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      [...],
      "atom-autocomplete-php",
      "php-class-tree"
    ],
    "packagesWithKeymapsDisabled": [
      "regex-railroad-diagram"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
autocomplete-php, v0.3.7
linter-php, v1.1.6
linter-phpmd, v1.3.2
php-cs-fixer, v2.5.2
php-debug, v0.2.1
[...]

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Hopefully fixed in v0.2.2 - Released Today
