### ISSUE TITLE
Uncaught TypeError: helpers.escapeHtml is not a function

### ISSUE THREAD

**Issue by oschettler** [gwomacks/php-debug#114]
1. Started remote debugging session by 
    ````
    XDEBUG_CONFIG="idekey=wildcard remote_host=192.168.33.1 remote_port=9000" php script.php
    ````

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.1

### Stack Trace

Uncaught TypeError: helpers.escapeHtml is not a function

```
At /Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:155

TypeError: helpers.escapeHtml is not a function
    at ContextVariableView.module.exports.ContextVariableView.render (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:33:78)
    at ContextVariableView.module.exports.ContextVariableView.initialize (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:12:6)
    at ContextVariableView.View [as constructor] (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ContextVariableView (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:7:3)
    at ContextVariableListView.module.exports.ContextVariableListView.render (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:27:41)
    at ContextVariableListView.module.exports.ContextVariableListView.initialize (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:19:6)
    at ContextVariableListView.View [as constructor] (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ContextVariableListView (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:8:3)
    at ContextVariableView.module.exports.ContextVariableView.render (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:46:34)
    at ContextVariableView.module.exports.ContextVariableView.initialize (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:12:6)
    at ContextVariableView.View [as constructor] (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ContextVariableView (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-view.coffee:7:3)
    at ContextVariableListView.module.exports.ContextVariableListView.render (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:27:41)
    at ContextVariableListView.module.exports.ContextVariableListView.initialize (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:19:6)
    at ContextVariableListView.View [as constructor] (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ContextVariableListView (/Users/olav/.atom/packages/php-debug/lib/context/context-variable-list-view.coffee:8:3)
    at ContextView.module.exports.ContextView.render (/Users/olav/.atom/packages/php-debug/lib/context/context-view.coffee:23:35)
    at ContextView.module.exports.ContextView.initialize (/Users/olav/.atom/packages/php-debug/lib/context/context-view.coffee:12:6)
    at ContextView.View [as constructor] (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ContextView (/Users/olav/.atom/packages/php-debug/lib/context/context-view.coffee:7:3)
    at PhpDebugContextView.module.exports.PhpDebugContextView.showContexts (/Users/olav/.atom/packages/php-debug/lib/context/php-debug-context-view.coffee:51:35)
    at /Users/olav/.atom/packages/php-debug/lib/context/php-debug-context-view.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at GlobalContext.module.exports.GlobalContext.notifyContextUpdate (/Users/olav/.atom/packages/php-debug/lib/models/global-context.coffee:123:14)
    at /Users/olav/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:245:31
    at _fulfilled (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:796:13)
    at /Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:604:44
    at runSingle (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/Users/olav/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -4:52.7.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "php-debug": {}
}
```

### Installed Packages

```coffee
# User
atom-htmltidy, v2.2.0
atom-pair, v2.0.10
linter, v1.11.3
linter-php, v1.1.7
minimap, v4.19.0
php-debug, v0.2.1
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Several months old, please reopen if a reinstall of the plugin does not resolve the issue.
