### ISSUE TITLE
Failed to load the php-debug package

### ISSUE THREAD

**Issue by PointedEars** [gwomacks/php-debug#118]
**Atom Version**: 1.4.3
**System**: Debian GNU/Linux
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2

### Stack Trace

Failed to load the php-debug package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/behavior.js:7:13)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/emissary.js:4:13)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/node_modules/emissary/lib/emissary.js:14:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/php-debug/node_modules/event-kit/node_modules/grim/lib/grim.js:4:13)
```

### Commands

```
     -2:15.3.0 blur (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "es-navigation",
      "git-tabs",
      "git-grep",
      "symbols-tree-view",
      "branch-status"
    ],
    "packagesWithKeymapsDisabled": [
      "fold-comments"
    ],
    "themes": [
      "seti-ui",
      "lcars-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, vundefined
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.20.0
autocomplete-awk, v0.1.2
autocomplete-bibtex, v0.6.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.6.1
autocomplete-xml, v0.8.1
autoupdate-packages, v1.3.1
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.1.1
column-select, v0.2.0
compare-files, v0.6.2
css-snippets, v0.9.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
file-icons, v1.6.14
filesize, v0.4.2
fold-comments, v0.5.0
git-diff-details, v0.21.0
git-go, v1.0.1
git-hide, v0.1.2
git-log, v0.4.1
highlight-selected, v0.11.2
hyperclick, v0.0.35
hyperclick-php, v0.2.1
javascript-snippets, v1.2.0
js-hyperclick, v1.4.1
js-refactor, v0.6.0
keyboard-localization, v1.4.14
language-apache, v1.4.0
language-diff, v0.4.0
language-gettext, v0.6.1
language-latex, v0.6.1
language-sql-mysql, v0.3.1
latex, v0.29.0
latexer, v0.2.7
lcars-syntax, v0.0.1
line-count-status, v0.0.3
line-jumper, v0.14.1
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-chktex, v1.2.5
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jshint, v1.3.0
linter-less, v2.4.0
linter-mixed-indent, v1.1.0
linter-php, v1.1.8
linter-pylint, v1.2.0
linter-shellcheck, v1.1.0
linter-tidy, v2.1.0
linter-xmllint, vundefined
local-history, v3.2.3
method-separator, v0.1.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
move-status-items, v0.0.11
nav-panel, v0.0.11
navigate, v0.1.13
navigate-indent, v0.1.0
nuclide-find-references, v0.0.35
nuclide-url-hyperclick, v0.0.35
open-recent, v5.0.0
php-debug, v0.2.2
php-extract-method, v0.2.1
php-getters-setters, v0.5.5
pigments, v0.23.1
project-view, vundefined
punchclock, v0.6.5
python-isort, v0.0.7
python-tools, v0.6.7
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.1
remote-edit, v1.8.24
revert-buffer, v0.5.0
seti-ui, v0.8.1
svn, v0.0.9
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
up2date, v0.1.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.19.1
w3c-validation, v0.4.0
xkcd-comics, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Likely a failed install, closing. Reopen if a reinstall does not solve.
