### ISSUE TITLE
Uncaught TypeError: editor.gutterWithName is not a function

### ISSUE THREAD

**Issue by Willian-Zhang** [gwomacks/php-debug#119]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2

### Stack Trace

Uncaught TypeError: editor.gutterWithName is not a function

```
At /Users/Willian/.atom/packages/php-debug/lib/php-debug.coffee:309

TypeError: editor.gutterWithName is not a function
    at Object.module.exports.PhpDebug.createGutter (/Users/Willian/.atom/packages/php-debug/lib/php-debug.coffee:309:16)
    at Object.module.exports.PhpDebug.toggleDebugging (/Users/Willian/.atom/packages/php-debug/lib/php-debug.coffee:347:8)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (/Users/Willian/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:22.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -6:21.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:12.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:12.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:44.6.0 php-debug:clearAllBreakpoints (atom-text-editor.editor.is-focused)
     -5:40.4.0 php-debug:clearAllWatchpoints (atom-text-editor.editor.is-focused)
     -5:30 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "es-navigation",
      "linter-jscs",
      "jshint",
      "language-javascript-jsx",
      "linter-jsxhint",
      "language-babel",
      "linter-eslint"
    ],
    "themes": [
      "atom-material-ui",
      "xcode-syntax"
    ]
  },
  "php-debug": {
    "GutterPosition": "Left",
    "PhpException": {
      "Notice": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.1
auto-indent, v0.5.0
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
commentcode, v0.1.0
ctags-status, v1.3.4
editorconfig, v1.2.4
language-jade, v0.6.3
language-matlab, v0.2.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-jshint, v1.3.0
linter-php, v1.1.8
method-separator, v0.1.4
node-debugger, v1.3.2
php-analyser, v0.2.0
php-debug, v0.2.2
php-integrator-annotations, v0.2.4
php-integrator-autocomplete-plus, v0.5.1
php-integrator-navigation, v0.4.0
php-integrator-tooltips, v0.3.1
react, v0.14.1
space-tab, v0.4.2
wakatime, v5.0.2
xcode-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by giorgiofellipe** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Windows 8.1
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2


### Stack Trace

Uncaught TypeError: editor.gutterWithName is not a function

```
At /C:/Users/giorgio-62/.atom/packages/php-debug/lib/php-debug.coffee:549

TypeError: editor.gutterWithName is not a function
    at Object.module.exports.PhpDebug.createGutter (file:///C:/Users/giorgio-62/.atom/packages/php-debug/lib/php-debug.coffee:309:16)
    at Object.module.exports.PhpDebug.toggleDebugging (file:///C:/Users/giorgio-62/.atom/packages/php-debug/lib/php-debug.coffee:347:8)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (file:///C:/Users/giorgio-62/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (C:\Users\giorgio-62\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (C:\Users\giorgio-62\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\giorgio-62\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "php-debug": {
    "PhpException": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
color-picker, v2.1.1
file-icons, v1.6.14
minimap, v4.19.0
php-debug, v0.2.2
php-twig, v4.0.0
svn, v0.0.9

# Dev
No dev packages
```

**Comment by raciniak** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2


### Stack Trace

Uncaught TypeError: editor.gutterWithName is not a function

```
At /home/username/.atom/packages/php-debug/lib/php-debug.coffee:309

TypeError: editor.gutterWithName is not a function
    at Object.module.exports.PhpDebug.createGutter (/home/username/.atom/packages/php-debug/lib/php-debug.coffee:309:16)
    at Object.module.exports.PhpDebug.toggleDebugging (/home/username/.atom/packages/php-debug/lib/php-debug.coffee:347:8)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (/home/username/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:36 core:save (div.package-detail.panels-item)
     -1:52.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-seti.theme-seti-ui)
  2x -1:02.2.0 core:save (atom-text-editor#php-debug.PathMaps.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-gfm",
      "language-csharp",
      "language-java"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "php-debug": {
    "PathMaps": [
      "/vat/www/myProject/"
    ],
    "ServerPort": 11111
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
autoclose-html, v0.23.0
autocomplete-jquery-mobile, v0.2.2
autocomplete-json, v1.9.1
autocomplete-php, v0.3.7
autocomplete-plus, v2.29.1
jQuery, v1.2.1
jquery-snippets, v11.0.0
language-ini, v1.14.0
language-markdown, v0.11.0
language-pascal, v0.17.0
language-smarty-php, v0.5.0
linter, v1.11.3
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-php, v1.2.0
minimap, v4.20.0
monokai-seti, v0.7.0
open-recent, v5.0.0
php-debug, v0.2.2
php-getters-setters, v0.5.5
php-integrator-autocomplete-plus, v0.5.2
php-twig, v4.0.0
pigments, v0.24.5
robin-language-php, v0.9.0
seti-icons, v0.4.5
seti-ui, v0.9.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by vallieres** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2


### Stack Trace

Uncaught TypeError: editor.gutterWithName is not a function

```
At /Users/alexandre.vallieres-legace/.atom/packages/php-debug/lib/php-debug.coffee:309

TypeError: editor.gutterWithName is not a function
    at Object.module.exports.PhpDebug.createGutter (/Users/alexandre.vallieres-legace/.atom/packages/php-debug/lib/php-debug.coffee:309:16)
    at Object.module.exports.PhpDebug.toggleDebugging (/Users/alexandre.vallieres-legace/.atom/packages/php-debug/lib/php-debug.coffee:347:8)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (/Users/alexandre.vallieres-legace/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:48.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -0:47.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:41.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:41.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  8x -0:41 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:21.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -0:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "seti-ui",
      "an-old-hope-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
an-old-hope-syntax, v0.5.0
atom-autocomplete-php, v0.18.7
atom-ctags, v4.5.2
autocomplete-ctags, v0.4.0
color-picker, v2.1.1
docblockr, v0.7.3
linter, v1.11.4
linter-php, v1.2.0
php-debug, v0.2.2
project-manager, v2.9.3
seti-ui, v0.9.2
sort-lines, v0.14.0
symbol-gen, v1.0.0

# Dev
No dev packages
```
