### ISSUE TITLE
Failed to load the php-debug package - event-kit

### ISSUE THREAD

**Issue by JavaScriptDude** [gwomacks/php-debug#141]
**Atom Version**: 1.5.3
**System**: OpenSuse GNU/Linux
**Thrown** From: php-debug package, v0.2.2

### Stack Trace

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/tquinn/_t/inst/php-debug-0.2.2/lib/php-debug.coffee:2:13)
    at Object.<anonymous> (/home/tquinn/_t/inst/php-debug-0.2.2/lib/php-debug.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at /usr/share/atom/resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

Commands

     -2:15.3.0 blur (div.settings-view.pane-item)
Config

{
  "core": {
    "disabledPackages": [
      "es-navigation",
      "git-tabs",
      "git-grep",
      "symbols-tree-view",
      "branch-status"
    ],
    "packagesWithKeymapsDisabled": [
      "fold-comments"
    ],
    "themes": [
      "seti-ui",
      "lcars-syntax"
    ]
  }
}

Installed Packages

Built-in Atom packages (89)
├── about@1.3.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.25.0
├── autocomplete-snippets@1.9.0
├── autoflow@0.26.0
├── autosave@0.23.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.0
├── bracket-matcher@0.79.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.195.0
├── fuzzy-finder@0.94.0
├── git-diff@0.57.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.0
├── image-view@0.56.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.51.1
├── language-clojure@0.19.1
├── language-coffee-script@0.46.0
├── language-csharp@0.11.0
├── language-css@0.36.0
├── language-gfm@0.82.0
├── language-git@0.11.0
├── language-go@0.42.0
├── language-html@0.44.0
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.105.0
├── language-json@0.17.3
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.36.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.45.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.2
├── language-yaml@0.25.0
├── line-ending-selector@0.3.0
├── link@0.31.0
├── markdown-preview@0.157.1
├── metrics@0.53.1
├── notifications@0.62.1
├── one-dark-syntax@1.1.2
├── one-dark-ui@1.1.9
├── one-light-syntax@1.1.2
├── one-light-ui@1.1.9
├── open-on-github@0.40.0
├── package-generator@0.41.0
├── settings-view@0.232.3
├── snippets@1.0.1
├── solarized-dark-syntax@0.39.0
├── solarized-light-syntax@0.23.0
├── spell-check@0.65.0
├── status-bar@0.80.0
├── styleguide@0.45.0
├── symbols-view@0.110.1
├── tabs@0.88.0
├── timecop@0.33.0
├── tree-view@0.198.1
├── update-package-dependencies@0.10.0
├── welcome@0.33.0
├── whitespace@0.32.1
└── wrap-guide@0.38.1

~/.atom/packages (1)
└── php-debug@0.2.2

**Comment by JavaScriptDude** [comment]
Duplicate of https://github.com/gwomacks/php-debug/issues/68

**Comment by tianshanghuo** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3


### Stack Trace

Failed to load the php-debug package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\beargan\.atom\packages\php-debug\lib\php-debug.coffee:2:13)
  at Object.<anonymous> (C:\Users\beargan\.atom\packages\php-debug\lib\php-debug.coffee:1:1)
  at Module._compile (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
  at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:117:28
  at Package.module.exports.Package.measure (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:457:14)
  at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:402:19
  at Config.module.exports.Config.transact (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:397:19)
  at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:743:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "activate-power-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
php-debug, v0.2.3
php-hyperclick, v1.0.0
php-integrator-navigation, v0.7.1
python-tools, v0.6.7
tree-view-finder, v0.2.1

# Dev
No dev packages
```
