### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getStack' of undefined

### ISSUE THREAD

**Issue by yriveiro** [gwomacks/php-debug#156]
[Enter steps to reproduce below:]

1. Press continue button

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getStack' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:155

TypeError: Cannot read property 'getStack' of undefined
    at PhpDebugStackView.module.exports.PhpDebugStackView.showStackFrames (/Users/yriveiro/.atom/packages/php-debug/lib/stack/php-debug-stack-view.coffee:34:5)
    at /Users/yriveiro/.atom/packages/php-debug/lib/stack/php-debug-stack-view.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at GlobalContext.module.exports.GlobalContext.notifyContextUpdate (/Users/yriveiro/.atom/packages/php-debug/lib/models/global-context.coffee:123:14)
    at /Users/yriveiro/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:246:31
    at _fulfilled (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:796:13)
    at /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:604:44
    at runSingle (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -8:44.6.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -8:42.4.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -8:42.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -8:37.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -8:27.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-seti-syntax.theme-atom-dark-ui)
     -7:14.6.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -7:13.1.0 core:paste (atom-text-editor.editor.is-focused)
     -7:12.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -7:12.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -6:58.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-seti-syntax.theme-atom-dark-ui)
     -5:44.6.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -5:43.1.0 core:paste (atom-text-editor.editor.is-focused)
     -5:42.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:42.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:41.4.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -5:03.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-seti-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/yriveiro/Development/github",
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "php-debug": {
    "MaxChildren": 512,
    "MaxData": 2048,
    "MaxDepth": 8,
    "PathMaps": [
      "/var/www/webcare;/Users/yriveiro/Development/byside/webcare/web"
    ],
    "PhpException": {
      "StrictStandards": false
    },
    "ServerPort": 9100
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.29.2
atom-cli-diff, v1.3.0
atom-html-preview, v0.1.19
atom-jade, v0.3.0
atom-pair, v2.0.10
autocomplete-go, v1.0.6
autocomplete-paths, v1.0.2
build, v0.59.0
build-gulp, v0.7.0
builder-go, v1.0.0
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.3.0
environment, v1.2.0
file-icons, v1.7.2
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
inline-messenger, v1.2.8
java-importer, v1.4.1
language-rust, v0.4.6
linter, v1.11.4
linter-javac, v1.8.1
linter-jsonlint, v1.2.3
linter-php, v1.2.0
linter-rust, v0.4.5
linter-shellcheck, v1.1.0
local-history, v3.2.3
minimap, v4.21.0
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.2.0
minimap-split-diff, v0.3.0
multi-wrap-guide, v0.23.5
navigator-godef, v1.0.2
php-cs-fixer, v2.5.6
php-debug, v0.2.2
php-twig, v4.0.0
phpunit, v1.2.0
phpunit-snippets, v0.1.0
pigments, v0.26.0
pretty-json, v1.0.3
project-manager, v2.9.7
react, v0.15.0
relative-numbers, v0.5.1
remote-edit, v1.8.24
seti-syntax, v0.4.2
sync-settings, v0.7.2
synced-sidebar, v0.4.3
term3, v0.21.4
tester-go, v1.0.4
travis-ci-status, v1.0.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
I believe this should be fixed in the latest release. Can get reopened if not.
