### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by tianshanghuo** [gwomacks/php-debug#162]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3

### Stack Trace

Failed to load the php-debug package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/beargan/.atom/packages/php-debug/lib/php-debug.coffee:2:13)
    at Object.<anonymous> (file:///C:/Users/beargan/.atom/packages/php-debug/lib/php-debug.coffee:1:1)
    at Module._compile (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\beargan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "activate-power-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
php-debug, v0.2.3
php-hyperclick, v1.0.0
php-integrator-navigation, v0.7.1
python-tools, v0.6.7
tree-view-finder, v0.2.1

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Issue from May closing. Sounds like a faulty install, a reinstall should resolve.
