### ISSUE TITLE
Uncaught TypeError: editor.getSelectedText is not a function

### ISSUE THREAD

**Issue by UziTech** [gwomacks/php-debug#170]
[Enter steps to reproduce below:]
1. Right click on input in settings

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3
### Stack Trace

Uncaught TypeError: editor.getSelectedText is not a function

```
At /C:/Users/tjbrix/.atom/packages/php-debug/lib/php-debug.coffee:370

TypeError: editor.getSelectedText is not a function
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (file:///C:/Users/tjbrix/.atom/packages/php-debug/lib/php-debug.coffee:196:34)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\context-menu-manager.js:110:19)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\context-menu-manager.js:89:33)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\context-menu-manager.js:168:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -7:50.3.0 core:select-all (atom-text-editor.editor.power-mode.is-focused.hyperclick)
     -7:50 core:copy (atom-text-editor.editor.power-mode.is-focused.hyperclick)
     -7:42.2.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
  5x -7:27.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -7:16.2.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
  4x -7:14.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -5:47.8.0 core:copy (atom-text-editor.editor.power-mode.is-focused.hyperclick)
  3x -3:09.8.0 core:delete (atom-text-editor.editor.power-mode.is-focused)
     -2:02.6.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -1:58.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.power-mode.is-focused)
     -1:56.1.0 settings-view:open (atom-text-editor.editor.power-mode)
  2x -0:42.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.power-mode.is-focused)
     -0:33.6.0 core:backspace (atom-text-editor#atom-beautify.php.phpcbf_path.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "command-executor",
      "linter-tidy",
      "linter-csslint",
      "git-diff-details",
      "emmet-snippets-compatibility",
      "jsformat",
      "php-integrator-symbol-viewer",
      "semanticolor"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "git-time-machine",
      "atom-beautify",
      "sass-autocompile",
      "linter",
      "hyperclick",
      "git-control",
      "emmet",
      "git-diff-details",
      "keybinding-cheatsheet",
      "bottom-dock",
      "linter-manager",
      "php-cs-fixer",
      "split-diff",
      "activate-power-mode",
      "grammar-selector",
      "markdown-preview",
      "highlight-selected",
      "change-case",
      "node-debugger"
    ]
  },
  "php-debug": {
    "GutterBreakpointToggle": false,
    "GutterPosition": "Left"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-beautify, v0.29.8
atom-jasmine, v0.8.1
atomic-chrome, v0.3.0
auto-detect-indentation, v1.1.0
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.0.3
cursor-history, v0.5.9
docblockr, v0.7.3
double-tag, v0.2.0
emmet, v2.4.3
file-icons, v1.7.15
file-types, v0.5.1
flex-tool-bar, v0.10.2
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-php, v0.2.1
hyperlink-hyperclick, v1.3.3
js-hyperclick, v1.4.2
language-babel, v2.28.0
language-batch, v0.3.3
language-ini, v1.16.0
line-diff-details, v1.3.5
line-ending-converter, v1.3.2
linter, v1.11.10
linter-coffeelint, v1.1.2
linter-eslint, v7.2.2
linter-htmlhint, v1.2.0
linter-js-yaml, v1.2.5
linter-markdown, v1.5.2
linter-phpcs, v1.4.0
linter-sass-lint, v1.6.0
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
minimap-split-diff, v0.3.1
node-debugger, v1.7.0
open_in_cmd, v0.6.1
php-debug, v0.2.3
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.1
php-integrator-base, v0.9.3
php-integrator-call-tips, v0.2.4
php-integrator-linter, v0.3.0
php-integrator-navigation, v0.7.1
php-integrator-tooltips, v0.6.1
pigments, v0.29.2
platformio-ide-terminal, v2.0.10
process-palette, v0.8.1
project-manager, v2.9.7
react, v0.15.0
Remote-FTP, v0.8.3
rest-client, v1.1.1
sass-autocompile, v0.12.7
Sublime-Style-Column-Selection, v1.5.1
tabasco, v0.5.0
tabs-to-spaces, v1.0.2
text-manipulation, v0.6.0
tool-bar, v0.4.0
trailing-spaces, v0.3.2
tree-view-git-status, v1.0.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Addressed in 1da5e87b will land in 0.2.4
