### ISSUE TITLE
Install Fails - undefined is not a function

### ISSUE THREAD

**Issue by jtmurphy1k** [gwomacks/php-debug#187]
Atom fails to install php-debug. php -m shows xdebug loaded under PHP and Zend Modules.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3
### Stack Trace

Failed to activate the php-debug package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.PhpDebug.createGutters (/home/jim/.atom/packages/php-debug/lib/php-debug.coffee:295:23)
  at /home/jim/.atom/packages/php-debug/lib/php-debug.coffee:186:8
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
  at Object.module.exports.PhpDebug.activate (/home/jim/.atom/packages/php-debug/lib/php-debug.coffee:185:17)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:222:19)
  at /usr/share/atom/resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:77:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -2:51.8.0 php-debug:run (atom-text-editor.editor)
     -2:08.2.0 core:move-right (atom-text-editor.editor)
  5x -2:07.8.0 core:delete (atom-text-editor.editor)
```

**Comment by cchamplin** [comment]
Should be resolved in f438167, will land in 0.2.4
