### ISSUE TITLE
Uncaught ReferenceError: gutter is not defined

### ISSUE THREAD

**Issue by 4nik8r** [gwomacks/php-debug#194]
To reproduce the error

1. I have a clean install of Atom 1.12.0
2. Install php-debug
3. Press ALT+F9 to toggle breakpoint.

This seems to confirm issue  #186 

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Ubuntu 16.04.1
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3

### Stack Trace

Uncaught ReferenceError: gutter is not defined

```
At /home/joel/.atom/packages/php-debug/lib/models/breakpoint-marker.coffee:8

ReferenceError: gutter is not defined
    at new BreakpointMarker (/home/joel/.atom/packages/php-debug/lib/models/breakpoint-marker.coffee:8:25)
    at Object.addBreakpointMarker (/home/joel/.atom/packages/php-debug/lib/php-debug.coffee:262:18)
    at Object.toggleBreakpoint (/home/joel/.atom/packages/php-debug/lib/php-debug.coffee:405:17)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleBreakpoint (/home/joel/.atom/packages/php-debug/lib/php-debug.coffee:117:94)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1126:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -7:16.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:23.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -4:19.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  9x -1:46.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:44.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:44.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:41.2.0 core:save (atom-text-editor.editor.is-focused)
 16x -1:40.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:35.7.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
     -0:58.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:48.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 22x -0:35.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:23.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.7.0 php-debug:toggleDebugging (atom-text-editor.editor)
     -0:00.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
php-debug, v0.2.3 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 4nik8r** [comment]
Earlier versions seem to be broken too. I've tested as far back as 1.10.2.

But I have found that temporary solution just in case others are looking for a quick fix. Go to php-debug settings and untick "Enable breakpoint markers in the gutter"

**Comment by WolfieZero** [comment]
@4nik8r That fixes it for me :)

**Comment by philprobinson84** [comment]
@4nik8r, @WolfieZero fixes it for me too. Worth noting that I still get a line marker for a breakpoint, see attached.
![php-debug-breakpoint](https://cloud.githubusercontent.com/assets/1550779/20215567/fc3f4d70-a80c-11e6-831a-3e560faf6f52.png)

**Comment by sbrl** [comment]
If I untick that then I don't get any breakpoint markers.

**Comment by WolfieZero** [comment]
@sbrl Could it be your theme? Does it show if you're using One Dark for both syntax and UI?

**Comment by sbrl** [comment]
I'm using "One Dark" for both my UI theme and my syntax theme, and it's still nto showing.

**Comment by sbrl** [comment]
Huh. That's odd. It displays in a test file correctly, even with that option turned off. It must be that it's clashing the the extension that shows the git line status in the gutter.

![image](https://cloud.githubusercontent.com/assets/9929737/20302162/1d6d231e-ab1e-11e6-993a-d9bf2be8fe52.png)

**Comment by 4nik8r** [comment]
@sbrl Directly below "Enable breakpoint marker..." in settings there is "Gutter Position".

By default my was set to "Right" but I had originally changed it to "Left". Testing now doesn't seem to make a difference but but this will have an effect on your setup?

**Comment by miclaus** [comment]
+1 
Can't set breakpoints.
I'm using Nuclide.

**Comment by mcarpenterjr** [comment]
+1
Can't set breakpoints.
This is a new error, was able to set break points before holiday.

**Comment by cchamplin** [comment]
The release with this fixed should be live as of today.

**Comment by 4nik8r** [comment]
Confirmed working. Many thanks :)
