### ISSUE TITLE
Uncaught TypeError: ref1.destroy is not a function

### ISSUE THREAD

**Issue by Ryohu** [gwomacks/php-debug#197]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.5
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.3

### Stack Trace

Uncaught TypeError: ref1.destroy is not a function

```
At /Users/ryo_hashimoto/.atom/packages/php-debug/lib/php-debug.coffee:341

TypeError: ref1.destroy is not a function
    at Object.toggleDebugging (/Users/ryo_hashimoto/.atom/packages/php-debug/lib/php-debug.coffee:341:22)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (/Users/ryo_hashimoto/.atom/packages/php-debug/lib/php-debug.coffee:119:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1142:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -6:52.7.0 core:close (atom-pane.pane.active)
     -6:31 settings-view:open (atom-text-editor.editor.is-focused)
  2x -5:01.3.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
 28x -4:08.0 core:backspace (atom-text-editor#php-debug.PathMaps.editor.mini.is-focused)
     -3:27.2.0 core:undo (atom-text-editor.editor.is-focused)
  5x -2:29.6.0 php-debug:addWatch (atom-text-editor.editor.is-focused)
     -2:13.8.0 find-and-replace:show (div.php-debug)
  3x -2:11.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:57.5.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
     -1:51.4.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
     -1:47 php-debug:breakpointSettings (atom-text-editor.editor.is-focused)
  2x -1:33.9.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
     -0:43.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:00.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "packagesWithKeymapsDisabled": [
      "php-debug"
    ],
    "telemetryConsent": "limited"
  },
  "php-debug": {
    "AutoExpandLocals": true,
    "GutterBreakpointToggle": false,
    "GutterPosition": "Left"
  }
}
```

### Installed Packages

```coffee
# User
php-debug, v0.2.3 (active)
platformio-ide-terminal, v2.2.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Should  be fixed in v0.2.4
