### ISSUE TITLE
Uncaught TypeError: other.getPath is not a function

### ISSUE THREAD

**Issue by djdesign** [gwomacks/php-debug#215]
1. Working on blade template, added breakpoint clicked another section above or below triggers immediate error.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package 0.2.4

### Stack Trace

Uncaught TypeError: other.getPath is not a function

```
At /Users/DJ/.atom/packages/php-debug/lib/models/breakpoint.coffee:95

TypeError: other.getPath is not a function
    at Breakpoint.module.exports.Breakpoint.isEqual (/packages/php-debug/lib/models/breakpoint.coffee:95:27)
    at Object.exports.arraySearch (/packages/php-debug/lib/helpers.coffee:32:15)
    at Object.exports.arrayRemove (/packages/php-debug/lib/helpers.coffee:37:19)
    at GlobalContext.module.exports.GlobalContext.removeBreakpoint (/packages/php-debug/lib/models/global-context.coffee:44:23)
    at Object.toggleBreakpoint (/packages/php-debug/lib/php-debug.coffee:433:30)
    at /packages/php-debug/lib/php-debug.coffee:351:8)
    at HTMLDivElement.dispatch (/packages/php-debug/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/php-debug/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:27.1.0 snippets:expand (input.hidden-input)
     -0:27.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:27.1.0 snippets:expand (input.hidden-input)
     -0:27.1.0 editor:indent (input.hidden-input)
     -0:26.7.0 snippets:expand (input.hidden-input)
     -0:26.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:26.7.0 snippets:expand (input.hidden-input)
     -0:26.7.0 editor:indent (input.hidden-input)
     -0:22.2.0 snippets:expand (input.hidden-input)
     -0:22.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:22.2.0 snippets:expand (input.hidden-input)
     -0:22.2.0 editor:indent (input.hidden-input)
     -0:21.9.0 snippets:expand (input.hidden-input)
     -0:21.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:21.9.0 snippets:expand (input.hidden-input)
     -0:21.9.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-clock 0.1.5 
atom-prettify 0.1.3 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.2 
bitbucket-issues 0.1.1 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
bootstrap4-snippets 0.2.2 
emmet 2.4.3 
emmet-simplified 2.5.0 
emmet-snippets-compatibility 1.0.6 
git-control 0.8.2 
jira-issue-search 1.0.3 
language-blade 0.28.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 1.11.23 
linter-php 1.3.1 
linter-phpcs 1.5.9 
linter-phpmd 1.5.3 
open-on-bitbucket 0.4.0 
php-cs-fixer 4.1.0 
php-debug 0.2.4 
php-refactoring 1.4.0 
v-bootstrap4 0.1.8 
wordpress-api 1.2.2 
wordpress-suite 0.4.5 
```

**Comment by aurovrata** [comment]
I am still getting this error
