### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by GabiArzu** [gwomacks/php-debug#249]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package 0.2.5

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At C:\Users\gabia_000\.atom\packages\php-debug\lib\php-debug.coffee:473

TypeError: editor.getPath is not a function
    at Object.toggleBreakpoint (/packages/php-debug/lib/php-debug.coffee:473:19)
    at /packages/php-debug/lib/php-debug.coffee:393:8)
    at HTMLDivElement.dispatch (/packages/save-session/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/save-session/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -0:33.1.0 core:backspace (input.hidden-input)
     -0:30.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:30.3.0 docblockr:parse-enter (input.hidden-input)
     -0:30.3.0 editor:newline (input.hidden-input)
  3x -0:28.2.0 core:backspace (input.hidden-input)
     -0:27.6.0 autoclose-html:close-and-complete (input.hidden-input)
  3x -0:27.1.0 core:backspace (input.hidden-input)
     -0:24 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:24 docblockr:parse-enter (input.hidden-input)
     -0:24 editor:newline (input.hidden-input)
     -0:18.2.0 intentions:highlight (input.hidden-input)
     -0:18 core:paste (input.hidden-input)
     -0:14.1.0 docblockr:parse-tab (input.hidden-input)
     -0:14.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:14.1.0 snippets:expand (input.hidden-input)
     -0:14.1.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
apex-syntax 0.2.0 
apex-ui 1.0.1 
ariake-dark-syntax 0.1.3 
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-monokai-php 1.0.0 
atomic-chrome 0.3.0 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
autoprefixer 3.6.1 
babel-react-syntax 1.2.0 
better-window-title 1.0.3 
blackboard 1.0.2 
blackboard-dark-mod 0.2.0 
color-picker 2.2.5 
colorblind-wombat-dark-syntax 0.6.0 
custom-window-title 1.0.4 
dark-flat-ui 1.2.4 
dash-syntax 0.4.0 
dash-ui 0.4.3 
docblockr 0.9.1 
dracula-theme 2.0.0 
dracula-ui 0.4.1 
duotone-light-syntax 2.1.0 
dusk-syntax 2.0.0 
eclectic-syntax 0.2.1 
emmet 2.4.3 
expose 0.13.0 
file-icons 2.1.12 
filecolor 0.4.0 
fizzy 0.21.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
glowing-cursor 0.1.2 
highlight-line 0.12.0 
highlight-selected 0.12.0 
hybrid-next-syntax 0.9.1 
Hydrogen 1.23.0 
hyperclick 0.1.5 
intentions 1.1.5 
ir-black-syntax 0.2.0 
isotope-light-ui 2.2.6 
linter 1.11.21 
linter-php 1.3.1 
min-ui 0.0.1 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
monokai-php-css-syntax 0.2.2 
monokai-seti 0.7.0 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
northem-atom-ui 2.0.0 
northem-dark-atom-syntax 2.0.0 
northem-dark-atom-ui 2.0.0 
obsidian-syntax 0.2.0 
oceanic-next 1.0.0 
one-dark-mini-ui 2.0.5 
one-dark-shade-ui 0.1.0 
one-dark-vivid-syntax 1.7.1 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.3 
qolor 0.4.1 
Remote-FTP 1.1.3 
rulerz 0.4.1 
seti-syntax 1.1.2 
seti-ui-beta 0.1.1 
seti-ui-red 0.13.0 
slim-dark-ui 0.12.0 
spacegray-black-syntax 0.1.4 
spacegray-dark-neue-ui 1.7.1 
spacegray-dark-ui 0.12.0 
title-bar-replacer 1.4.3 
todo-show 1.9.0 
toggle-quotes 1.0.0 
vertical-tabs 1.0.5 
```

**Comment by cchamplin** [comment]
Possibly fixed in v0.3.0. Please reopen if not.
