### ISSUE TITLE
Uncaught ReferenceError: _bufferIdx is not defined

### ISSUE THREAD

**Issue by costafrancesco94** [gwomacks/php-debug#280]
Hi :)

I have recently upgraded to 0.3.1 after that #277 was fixed, but when an error occour in the code while debugging (with no specific break point) the debugger crashes and canont move on anymore.

Stack Trace:
``
ReferenceError: _bufferIdx is not defined
    at DbgpInstance.parse (/home/francesco/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.js:158:27)
    at DbgpInstance.handleData (/home/francesco/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.js:275:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
``

PHP: PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 with Xdebug v2.6.0

Setup was working correctly before upgrade from 0.2.6 to 0.3.0 I think it's becouse of decoupling things i've read on... If this can help...

**Comment by cchamplin** [comment]
Yup typo on my part, 0.3.2 will probably land later today with the fix in it.
