### ISSUE TITLE
Uncaught SyntaxError: Unexpected token / in JSON at position 0

### ISSUE THREAD

**Issue by lisfox1** [gwomacks/php-debug#295]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package 0.3.4

### Stack Trace

Uncaught SyntaxError: Unexpected token / in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at DebbuggingContext.handlePathMapsClick (/packages/php-debug/lib/engines/dbgp/debugging-context.js:163:26)
    at /packages/php-debug/lib/engines/dbgp/debugging-context.js:66:18
    at HTMLButtonElement.result (/packages/atom-debug-ui/lib/actions/actionbar.js:125:7)
```

### Commands

```
     -0:52.1.0 command-palette:toggle (input.hidden-input)
     -0:48.4.0 intentions:highlight (input.hidden-input)
     -0:48.4.0 datatip:toggle (input.hidden-input)
     -0:48.2.0 editor:log-cursor-scope (input.hidden-input)
     -0:46.5.0 datatip:toggle (input.hidden-input)
     -0:43.5.0 core:select-up (input.hidden-input)
     -0:32.8.0 php-debug:run (input.hidden-input)
```

### Non-Core Packages

```
atom-debug-ui 1.0.4 
atom-ide-ui 0.11.2 
atom-phpunit 1.3.0 
busy-signal 1.4.3 
ide-php 0.7.14 
intentions 1.1.5 
linter 2.2.0 
linter-phpmd 2.0.0 
linter-ui-default 1.7.1 
php-debug 0.3.4 
```

**Comment by cchamplin** [comment]
Should be Fixed in v0.3.5. If not please reopen
