### ISSUE TITLE
TypeError: Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by aleclarson** [gwomacks/php-debug#307]
**"Failed to activate the php-debug package"**

When I enabled the `php-debug` package.

```
TypeError: Cannot read property 'debug' of undefined
    at ServiceManager.activate (/Users/aleclarsoniv/.atom/packages/atom-debug-ui/lib/services.js:66:36)
    at PHPDebug.consumeDebugUI (/Users/aleclarsoniv/.atom/packages/php-debug/lib/php-debug.js:232:22)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:452:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:254:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:97:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:34)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:685:36)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:45)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:691:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:882:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:668:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:246:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:405:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:82:26)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:240:12)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:353:25)
```

### Versions
```
atom v1.22.0
atom-debug-ui v1.0.4
php-debug v0.3.5
electron v1.6.15
macos v10.13 (17A405)
```

**Comment by aleclarson** [comment]
Duplicate of https://github.com/cchamplin/atom-debug-ui/issues/8

**Comment by aleclarson** [comment]
I'll keep this open, since I'm not sure if it's a `atom-debug-ui` or `php-debug` problem.
