### ISSUE TITLE
Uncaught TypeError: Cannot read property 'continue' of undefined

### ISSUE THREAD

**Issue by fobus42** [gwomacks/php-debug#42]
This error occurs when I click any function in the menu like Run, Step In, Step Over etc...
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [PHP-Debug](https://github.com/gwomacks/php-debug) package, v0.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'continue' of undefined

```
At /home/kervan/.atom/packages/PHP-Debug/lib/php-debug.coffee:143

TypeError: Cannot read property 'continue' of undefined
    at Object.module.exports.PhpDebug.stepOut (/home/kervan/.atom/packages/PHP-Debug/lib/php-debug.coffee:256:57)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:stepOut (/home/kervan/.atom/packages/PHP-Debug/lib/php-debug.coffee:114:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:157:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:73:30)
    at EventEmitter.emit (events.js:116:17)
```

### Commands

```
     -2:06.8 atom-terminal-panel:toggle (atom-text-editor.editor)
     -1:56.8 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:26.1 php-debug:run (atom-text-editor.editor)
     -0:12.9 php-debug:clearAllBreakpoints (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.7 php-debug:stepOut (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript"
    ]
  },
  "PHP-Debug": {}
}
```

### Installed Packages

```coffee
# User
PHP-Debug, v0.0.6
atom-terminal-panel, v4.4.4

# Dev
No dev packages
```

**Comment by luishdez** [comment]
It happens to me as well

**Comment by gwomacks** [comment]
This would happen when there was no active debugging session.
The error should no longer come up now.

**Comment by fobus42** [comment]
But how to start a debug session? I'm using Xdebug Helper with PHP storm works great. On port 9000
Do I need a configuration?

**Comment by gwomacks** [comment]
As long as the debugging view is open (ctrl-alt-d or 'Toggle Debugging' from the menu), it should accept incoming connections.
