### ISSUE TITLE
Error when breakpoint is triggered.

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#55]
Hello

Whenever a breakpoint is triggered I receive the following error (I just placed a breakpoint and then refreshed the page in the browser):

```
events.js:141
  at Function.keys (native)
  at /home/user/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:57:27
  at Parser.<anonymous> (/home/user/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:463:18)
  at emitOne (events.js:77:13)
  at Parser.emit (events.js:166:7)
  at Object.onerror (/home/user/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:292:26)
  at emit (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
  at error (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:644:3)
  at strictFail (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
  at end (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:649:27)
  at Object.write (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:916:30)
  at Object.SAXParser.close (/home/user/.atom/packages/php-debug/node_modules/xml2js/node_modules/sax/lib/sax.js:152:38)
  at Parser.exports.Parser.Parser.parseString (/home/user/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:478:42)
  at Parser.parseString (/home/user/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:6:59)
  at exports.parseString (/home/user/.atom/packages/php-debug/node_modules/xml2js/lib/xml2js.js:510:19)
  at DbgpInstance.module.exports.DbgpInstance.parse (/home/user/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:56:15)
  at DbgpInstance.parse (/home/user/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:1:1)
  at DbgpInstance.module.exports.DbgpInstance.stuff (/home/user/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:78:26)
  at Socket.<anonymous> (/home/user/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:1:1)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)
```

I'm running on Linux with version 0.1.2 of the plugin.

Thanks in advance

**Comment by cchamplin** [comment]
@Gert-dev is this still an issue in the latest release?

**Comment by Gert-dev** [comment]
I pulled from Git and this no longer seems to be an issue, thanks!
