### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by donCarlosOne** [gwomacks/php-debug#59]
[Enter steps to reproduce below:]

1. Set a breakpoint
2. Toggled php-debug on
3. requested page via chrome

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property '0' of undefined
  at /Users/doncarlos/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:263:70
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -7:39.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -7:37.3.0 url-encode:decode (atom-text-editor.editor.is-focused)
     -7:23.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -7:21.5.0 url-encode:decode (atom-text-editor.editor.is-focused)
  8x -7:11.8.0 core:page-up (atom-text-editor.editor.is-focused)
     -7:08.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:59.2.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
  2x -4:43.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:25.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:19.2.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
  6x -4:10.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:57.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -2:41.9.0 core:cut (atom-text-editor.editor.is-focused)
  4x -2:38.9.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:31.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:24.2.0 php-class-tree:rebuild (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-space-pen-views"
    ]
  },
  "php-debug": {}
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-beautify, v0.28.7
autocomplete-php, v0.3.6
color-picker, v2.0.7
jsformat, v0.9.0
language-php, v0.26.0
linter-php, v0.0.15
minimap, v4.10.1
php-class-tree, v1.0.0
php-debug, v0.1.2
php-getters-setters, v0.5.5
php-introspector, v1.0.0
php-twig, v4.0.0
pretty-json, v0.4.1
script, v2.26.0
url-encode, v0.5.0

# Dev
No dev packages
```

**Comment by Aclopes** [comment]
me too

**Comment by ChristianGrech** [comment]
+1

**Comment by cchamplin** [comment]
Is this issue still occurring?

**Comment by cchamplin** [comment]
No updates, closing
