### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by donCarlosOne** [gwomacks/php-debug#60]
[Enter steps to reproduce below:]

1. Toggled php-debug
2. Set a breakpoint from gutter.  Crash

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/doncarlos/.atom/packages/php-debug/lib/models/breakpoint.coffee:66

TypeError: undefined is not a function
  at Breakpoint.module.exports.Breakpoint.isEqual (/Users/doncarlos/.atom/packages/php-debug/lib/models/breakpoint.coffee:66:27)
  at Object.exports.arraySearch (/Users/doncarlos/.atom/packages/php-debug/lib/helpers.coffee:17:15)
  at Object.exports.arrayRemove (/Users/doncarlos/.atom/packages/php-debug/lib/helpers.coffee:22:19)
  at GlobalContext.module.exports.GlobalContext.removeBreakpoint (/Users/doncarlos/.atom/packages/php-debug/lib/models/global-context.coffee:43:23)
  at Object.module.exports.PhpDebug.toggleBreakpoint (/Users/doncarlos/.atom/packages/php-debug/lib/php-debug.coffee:231:30)
  at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleBreakpoint (/Users/doncarlos/.atom/packages/php-debug/lib/php-debug.coffee:102:94)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-space-pen-views",
      "tool-bar-main",
      "toolbar-basic",
      "atom-project",
      "project-ring",
      "project-switcher",
      "project-view",
      "project-quick-open",
      "autohide-tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "php-debug": {
    "PhpException": {
      "Deprecated": false,
      "FatalError": false,
      "Notice": false,
      "StrictStandards": false,
      "Warning": false
    }
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-ternjs, v0.6.7
autocomplete-php, v0.3.6
color-picker, v2.0.7
git-projects, v1.14.1
indent-guide-improved, v1.4.0
js-refactor, v0.4.2
jsformat, v0.9.0
jshint, v1.3.8
language-javascript-better, v1.5.0
language-php, v0.26.0
linter-js-standard, v1.0.4
linter-php, v0.0.15
local-history, v3.2.3
minimap, v4.10.1
php-debug, v0.1.2
php-getters-setters, v0.5.5
php-introspector, v1.0.0
php-twig, v4.0.0
pretty-json, v0.4.1
project-colorize, v0.2.0
project-manager, v1.15.10
recent-projects, v0.4.3
spec-tree-view, v0.1.0
symbols-tree-view, v0.9.3
synced-sidebar, v0.4.0
tool-bar, v0.1.8
toolbar-iconshortcuts, v0.3.0
tree-view-finder, v0.2.1
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by cpierce** [comment]
:+1:

**Comment by cchamplin** [comment]
Is this issue still occurring?
