### ISSUE TITLE
problems to open php-debug

### ISSUE THREAD

**Issue by gabrielvmp** [gwomacks/php-debug#68]
Failed to load the php-debug package
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/morenovg/.atom/packages/php-debug-0.1.2/lib/php-debug.coffee:6:13)
    at Object.<anonymous> (/home/morenovg/.atom/packages/php-debug-0.1.2/lib/php-debug.coffee:409:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
The error was thrown from the php-debug package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the php-debug package

**Comment by cchamplin** [comment]
Please try reinstalling, or running apm install in the module directory.
