### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::9000

### ISSUE THREAD

**Issue by ChristianGrech** [gwomacks/php-debug#75]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Home
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Uncaught Error: listen EADDRINUSE :::9000

```
At events.js:141

Error: listen EADDRINUSE :::9000
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1173:14)
    at listen (net.js:1203:10)
    at Server.listen (net.js:1290:5)
    at Dbgp.module.exports.Dbgp.listen (C:\Users\Christian\.atom\packages\php-debug\lib\engines\dbgp\dbgp.coffee:53:17)
    at Object.module.exports.PhpDebug.toggleDebugging (C:\Users\Christian\.atom\packages\php-debug\lib\php-debug.coffee:353:28)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (C:\Users\Christian\.atom\packages\php-debug\lib\php-debug.coffee:149:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:3:61)
```

### Commands

```
     -5:28.9.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -5:27.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.9
linter, v1.5.0
linter-php, v1.0.3
php-debug, v0.1.3
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yareckon** [comment]
This may indicate another package (in my case netbeans debugger), or another instance of php-debug listening on port 9000.  Close these other packages.

**Comment by rugk** [comment]
This still happens when you have opened two Atom windows with php-debug. Can't you somehow combine it so that only one instance listens on this port?
