### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ChristianGrech** [gwomacks/php-debug#77]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Home
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:128

TypeError: Cannot read property '0' of undefined
    at C:\Users\Christian\.atom\packages\php-debug\lib\engines\dbgp\dbgp-instance.coffee:431:45
    at _fulfilled (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:756:13)
    at C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:564:44
    at flush (C:\Users\Christian\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:110:17)
    at process._tickCallback (node.js:357:13)
```

### Commands

```
     -2:54.3.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -2:51.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:49.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.9
linter, v1.5.1
linter-php, v1.0.3
php-cs-fixer, v2.4.0
php-debug, v0.1.3
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by rzelnik** [comment]
I have the same issue. After upgrade of Atom to v1.0.19, this error occurs each time I click to Step Over, Step In or Step Out. No Stack, no Context, the whole php-debug plugin is useless.
