### ISSUE TITLE
Failed to activate the php-debug package

### ISSUE THREAD

**Issue by LuckyLuky** [gwomacks/php-debug#78]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Failed to activate the php-debug package

```
At Cannot find module 'xml2js'

Error: Cannot find module 'xml2js'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Lukáš\.atom\packages\php-debug\lib\engines\dbgp\dbgp.coffee:1:15)
  at Object.<anonymous> (C:\Users\Lukáš\.atom\packages\php-debug\lib\engines\dbgp\dbgp.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.PhpDebug.activate (C:\Users\Lukáš\.atom\packages\php-debug\lib\php-debug.coffee:120:12)
  at Package.module.exports.Package.activateNow (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:245:19)
  at C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Lukáš\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -1:45.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
minimap, v4.13.3
php-debug, v0.1.3
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Closing for now please reopen if a reinstall of the latest release does not resolve.

**Comment by rayfoss** [comment]
Had this issue on 0.2.4, on fedora 25 and Atom 1.12.6
