### ISSUE TITLE
Uncaught TypeError: editor.getSelectedBufferRange is not a function

### ISSUE THREAD

**Issue by martiis** [gwomacks/php-debug#79]
Just tried to toggle breakpoint. 

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.5
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Uncaught TypeError: editor.getSelectedBufferRange is not a function

```
At /Users/martynas/.atom/packages/php-debug/lib/php-debug.coffee:400

TypeError: editor.getSelectedBufferRange is not a function
  at Object.module.exports.PhpDebug.toggleBreakpoint (/Users/martynas/.atom/packages/php-debug/lib/php-debug.coffee:234:20)
  at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleBreakpoint (/Users/martynas/.atom/packages/php-debug/lib/php-debug.coffee:102:94)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  4x -1:46.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:41.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:38.4.0 core:close (atom-text-editor.editor.is-focused)
  6x -1:35.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.8.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
     -0:34.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:31.2.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:17.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.4.0 php-debug:toggleDebugging (atom-text-editor.editor)
     -0:04.7.0 command-palette:toggle (div.php-debug.php-debug-unified-view.pane-item.padded)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 php-debug:toggleBreakpoint (div.php-debug.php-debug-unified-view.pane-item.padded)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "metrics",
      "language-toml",
      "language-perl",
      "language-objective-c",
      "language-java",
      "language-c",
      "language-csharp"
    ],
    "followSymlinks": false,
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "php-debug": {
    "ServerPort": 9090
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-autocomplete-php, v0.10.11
atom-jinja2, v0.5.0
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.9
git-control, v0.3.0
language-ansible, v0.1.3
language-docker, v1.1.3
language-puppet, v0.14.0
minimap, v4.13.3
php-debug, v0.1.3
php-twig, v4.0.0
project-manager, v2.5.1

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Should be fixed in #89
