### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by maaarghk** [gwomacks/php-debug#84]
This happens when a breakpoint is reached

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at eval (native)
  at Function.jQuery.extend.globalEval (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:328:5)
  at [object Object].jQuery.fn.extend.domManip (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:5435:16)
  at [object Object].jQuery.fn.extend.append (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:5218:15)
  at PhpDebugContextView.module.exports.PhpDebugContextView.showContexts (/Users/Mark/.atom/packages/php-debug/lib/context/php-debug-context-view.coffee:38:24)
  at /Users/Mark/.atom/packages/php-debug/lib/context/php-debug-context-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at GlobalContext.module.exports.GlobalContext.notifyContextUpdate (/Users/Mark/.atom/packages/php-debug/lib/models/global-context.coffee:114:14)
  at /Users/Mark/.atom/packages/php-debug/lib/engines/dbgp/dbgp-instance.coffee:230:31
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -5:00.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:52.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:51 core:backspace (atom-text-editor.editor.is-focused)
     -4:50.1.0 core:delete (atom-text-editor.editor.is-focused)
     -4:49.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -4:49 core:move-left (atom-text-editor.editor.is-focused)
  2x -4:48.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:48.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:54.2.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -2:46.8.0 core:close (div.settings-view.pane-item)
     -2:19.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:28.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:28.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:26.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:33.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "auto-indent-file",
      "symbols-view",
      "symbol-gen"
    ]
  },
  "php-debug": {
    "PathMaps": [
      {
        "local": "/Users/xxxx/Development/Projects/yyyy",
        "remote": "/home/zzzz/projects/yyyy"
      }
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.14.0
atom-ctags, v4.3.0
auto-indent, v0.5.0
autocomplete-ctags, v0.3.2
autocomplete-php, v0.3.7
docblockr, v0.7.3
git-diff-details, v0.20.0
jshint, v1.8.0
language-diff, v0.3.1
language-javascript-jsx, v0.3.7
linter, v1.8.1
linter-php, v1.0.5
minimap, v4.13.4
php-debug, v0.1.3

# Dev
No dev packages
```

**Comment by cchamplin** [comment]
Should be corrected in the latest release.
