### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::19000

### ISSUE THREAD

**Issue by rubinred** [gwomacks/php-debug#90]
I use a vagrant box to run my code. Mapped port 9000 in guest to port 19000 in host.
Click Toggle debugging.

My xdebug configuration is as follow:

zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_connect_back=1    # Not safe for production servers
xdebug.remote_port=9000
xdebug.scream=0 
xdebug.cli_color=1
xdebug.show_local_vars=1

Those settings work well using NetBeans or PhpStorm.
Address will always be in use because VirtualBox listen on that port to forward packets to guest.

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.3

### Stack Trace

Uncaught Error: listen EADDRINUSE :::19000

```
At events.js:141

Error: listen EADDRINUSE :::19000
  at Object.exports._errnoException (util.js:814:11)
  at exports._exceptionWithHostPort (util.js:837:20)
  at Server._listen2 (net.js:1214:14)
  at listen (net.js:1250:10)
  at Server.listen (net.js:1340:5)
  at Dbgp.module.exports.Dbgp.listen (/home/workup/.atom/packages/php-debug/lib/engines/dbgp/dbgp.coffee:38:7)
  at Object.module.exports.PhpDebug.toggleDebugging (/home/workup/.atom/packages/php-debug/lib/php-debug.coffee:195:15)
  at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (/home/workup/.atom/packages/php-debug/lib/php-debug.coffee:103:93)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -9:59.9.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
  2x -9:36.3.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
     -2:31.2.0 editor:delete-to-end-of-subword (atom-text-editor.editor.is-focused)
     -2:30.3.0 core:undo (atom-text-editor.editor.is-focused)
  4x -2:23.6.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "linter-phpmd",
      "tabs-to-spaces",
      "linter-jscs",
      "atom-ctags"
    ],
    "packagesWithKeymapsDisabled": [
      "project-viewer"
    ]
  },
  "php-debug": {
    "PathMaps": [
      {
        "local": "/home/workup/www/tests/rrtest",
        "remote": "/var/www/html/tests/rrtest"
      }
    ],
    "ServerPort": 19000
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-autocomplete-php, v0.18.1
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
color-picker, v2.0.13
docblockr, v0.7.3
editorconfig, v1.2.0
file-icons, v1.6.11
highlight-selected, v0.10.1
language-blade, v0.16.0
linter, v1.9.1
linter-php, v1.0.5
linter-phpcs, v1.2.2
minimap, v4.15.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.1
php-cs-fixer, v2.5.1
php-debug, v0.1.3
pigments, v0.18.1
project-manager, v2.6.5
sync-settings, v0.6.0
synced-sidebar, v0.4.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by phaberest** [comment]
FYI in my case changing the port both in `launch.json` and in the `php.ini` solved the issue.
